### ISSUE TITLE
sampling qdisc stats from fq_codel

### ISSUE THREAD

**Issue by dtaht** [dankamongmen/omphalos#69]
I just ran across your tool today, whilst searching for a better curses library. Neat stuff.

I have always dreamed that more sysadmin folk could see pretty tcp sawtooths in real time, and other network behaviors like ecn packet marks, at the nyquist level (10ms sampling rate), in particular, on wifi. 

In my current project (libreqos) we are succeeding in doing that but so far writing the netlink required to do it that fast has eluded us, and leveraging tc -s -j qdisc show way too slow.  How good is your netlink-fu?

**Comment by dankamongmen** [comment]
i know netlink pretty well:

https://nick-black.com/dankwiki/index.php/Netlink
https://github.com/dankamongmen/libnetstack

i actually just submitted a kernel patch against it yesterday, though this is by no means a regular occurrence.

but are you proposing something for omphalos, or just asking?

**Comment by dtaht** [comment]
Well, if I knew a good way to do it that fast, I´d run around trying to stick it into every tool I could find, including yours! Sawtooths are pretty. 

When we developed fq_codel and sch_cake, I mostly relied on printks to inspect the queue state, running at 100mbit. Nowadays we´re ubiquitous... pushing 20-100Gbit. For over a year now I have been getting reports however that cake´s cobalt AQM in particular, appears to be malfunctioning when faced with gso packets... (I think) so buried DEEP within there is a problem. I can, now, get it to glitch at about 500Mbit () *sometimes*... when faced with just the right kind of traffic...

![image](https://user-images.githubusercontent.com/108682/215938299-52158328-ec7d-49bb-8b35-6e0085c1518e.png)

It seems like tc qdisc show dumps the entire htb tree also, even if I specify a handle, and then parses it out in userspace.

I guess I would settle for just knowing there is no way to get back just the cake class (tin) I need?

thx for any insight you have, regardless. thx for the steer to your lib, but like all the others it doesnt get anywhere near the qdisc. :( 

PS I LOVE console tools in general, I really enjoyed reading up on what notcurses can do the other day.

**Comment by dankamongmen** [comment]
oh shit you're *that* Dave Täht!

**Comment by dankamongmen** [comment]
know that even as we write this, a patch of mine to move Microsoft "Mariner" hosts to CAKE by default is working its way through my employer! i had one of the original buffalo routers handed out by Nick Feamster's bufferbloat team at Georgia Tech, and have been following the bufferbloat effort with much fascination and hope for almost all its existence. nice to meet you, man!

**Comment by dankamongmen** [comment]
hah i sent http://blog.cerowrt.org/post/flaws_in_flent/ around to my team just two weeks ago (after reading it on LWN) with "here's a decent article about network testing, less bullshit than normal". sorry for the moment of fanboyism =]

**Comment by dtaht** [comment]
Nice to meet you as well, and also to hear that multiple crusaders are making progress towards killing the bloat.  You mean this project?

https://github.com/microsoft/CBL-Mariner

holy cow, that is awesome! (got any good stats back? :) )  

There definitely are some problems at above 500mbit, eero had em, I get reports all over of issues in the deployment, but no data...

**Comment by dtaht** [comment]
> 

I have one that I am trying to cut the cuss words out of, from a party I attended of fiber broadband people. Femptotrenching! I am enjoying being a BOFH again, there really has been too much BS in the world for the last few years.

**Comment by dtaht** [comment]
https://comcom.govt.nz/__data/assets/pdf_file/0028/295804/MBNZ-Spring-Report-2022-27-October-2022.pdf see fig 10. Still elides the tests that dont complete (survivorship bias), test doesnt show stuff past 4 seconds (because, networks never do that right ? ), and then it averages the medians and lumps technologies together rather than ISPs (there is a very good ISP in NZ running libreqos now that has barely measurable latency under load)... but it is an improvement over what we keep getting out of the FCC. Also got a good report leveraging some samknows data out of ofcom a few months back. Anyway, this is kind of off topic, but feel free to send that NZ report around. 

Any chance y'all can do some deep netlink on your pending deployment?

**Comment by dtaht** [comment]
btw despite my obsessions and perfectionism, I think cake is operating well in general, it just falls apart more on cheap cpus or on insanely high workloads than I would like. In particular, the gso-splitter could split at the quantum instead  of all the time, which I think would help... (at the cost of statistical accuracy) and I would like to take advantage of nick mckeowns latest insights in light of our improved and increasingly pacing protocols:  https://arxiv.org/pdf/2109.11693.pdf in a future revision of cake. (it is called babycake right now)

if you are replacing fifos with cake you aren't going to be as finicy as I! and just celebrate... Are you using the shaper or?

**Comment by dtaht** [comment]
Anyway, I would love to hear back as to how well the cake deployment goes?, but this bug is not particularly related to your backlog of issues. I'll let you know if I come up with an answer!

**Comment by dtaht** [comment]
@dankamongmen cannot help but wonder if cake made it in, given the azure announcement.
